baseurl = "http://mfojtik.io"
languageCode = "en-us"
title = "mfojtik blog"
log = true
relativeURL = true

[params]
  Subtitle = "Look at you, hacker. A pathetic creature of meat and bone, panting and sweating as you run through my corridors. How can you challenge perfect immortal machine"
  GithubID = "mfojtik"
  TwitterID = "mfojtik"
  DisqusShortname = "mfojtik"
  Summary = true
  Content = true
